name: Build and Deploy Blazor WebAssembly App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./MapRotationTimer/MapRotationTimer.csproj

      - name: Build
        run: dotnet publish -c Release -o build_output ./MapRotationTimer/MapRotationTimer.csproj

      - name: List build output
        run: ls -R build_output/wwwroot

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_output/wwwroot
